"""Tabel Mahasiswa

Revision ID: 9423aa8b2821
Revises: cb98afe06f9a
Create Date: 2022-12-15 11:27:31.006681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9423aa8b2821'
down_revision = 'cb98afe06f9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mahasiswa',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nidn', sa.String(length=10), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('alamat', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('dosen_satu', sa.BigInteger(), nullable=True),
    sa.Column('dosen_dua', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['dosen_dua'], ['dosen.id'], ),
    sa.ForeignKeyConstraint(['dosen_satu'], ['dosen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mahasiswa')
    # ### end Alembic commands ###
